"""The forensic Span envelope (BUILD_SPEC §2, Phase 1).

A :class:`Span` wraps one typed event payload with the identity every later
component and the replay/UI layer depend on:

* ``trace_id``       — 128-bit OTel trace id, 32 lowercase hex chars (= run id).
* ``span_id``        — 64-bit OTel span id, 16 lowercase hex chars.
* ``parent_span_id`` — the causal parent's span_id, or ``None`` for a trace root.
* ``seq``            — per-trace monotonic integer assigned at the proxy's single
  serialization point (the emitter). Replay orders by ``(trace_id, seq)`` — NOT
  by write-completion order, which under concurrent async writes is non-
  deterministic. ``seq`` is a SEPARATE field; it never replaces ``span_id``.

IDs are generated by the OTel SDK (``whence.tracing``), never hand-rolled
UUIDs — UI/replay interop with W3C Trace Context depends on the exact hex shape,
so the validators below enforce it loudly rather than trusting the caller.
"""
from __future__ import annotations

import re
from datetime import UTC, datetime
from typing import Final

from pydantic import BaseModel, ConfigDict, Field, field_validator

from whence.forensics.events import EventPayload

_TRACE_ID_RE: Final[re.Pattern[str]] = re.compile(r"\A[0-9a-f]{32}\Z")
_SPAN_ID_RE: Final[re.Pattern[str]] = re.compile(r"\A[0-9a-f]{16}\Z")
# All-zero ids are "invalid / no-trace" whences in W3C Trace Context.
_ZERO_TRACE_ID: Final[str] = "0" * 32
_ZERO_SPAN_ID: Final[str] = "0" * 16


def _utcnow() -> datetime:
    return datetime.now(UTC)


class Span(BaseModel):
    """One immutable forensic record: OTel identity + seq + a typed payload."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    trace_id: str
    span_id: str
    parent_span_id: str | None = None
    seq: int = Field(ge=0)
    timestamp: datetime = Field(default_factory=_utcnow)
    # Discriminated union — Pydantic picks the concrete payload by `event_type`.
    payload: EventPayload

    @property
    def event_type(self) -> str:
        """The discriminator of the wrapped payload (e.g. ``"ToolCallProposed"``)."""
        return self.payload.event_type

    @property
    def is_root(self) -> bool:
        return self.parent_span_id is None

    @field_validator("trace_id")
    @classmethod
    def _check_trace_id(cls, value: str) -> str:
        if not _TRACE_ID_RE.match(value):
            raise ValueError(
                f"trace_id must be 32 lowercase hex chars (W3C/OTel), got {value!r}"
            )
        if value == _ZERO_TRACE_ID:
            raise ValueError("trace_id must not be all-zero (W3C invalid whence)")
        return value

    @field_validator("span_id")
    @classmethod
    def _check_span_id(cls, value: str) -> str:
        if not _SPAN_ID_RE.match(value):
            raise ValueError(
                f"span_id must be 16 lowercase hex chars (W3C/OTel), got {value!r}"
            )
        if value == _ZERO_SPAN_ID:
            raise ValueError("span_id must not be all-zero (W3C invalid whence)")
        return value

    @field_validator("parent_span_id")
    @classmethod
    def _check_parent_span_id(cls, value: str | None) -> str | None:
        if value is None:
            return None
        if not _SPAN_ID_RE.match(value) or value == _ZERO_SPAN_ID:
            raise ValueError(
                "parent_span_id must be 16 lowercase hex chars or None, "
                f"got {value!r}"
            )
        return value
