"""OpenTelemetry tracer initialization for Whence.

BUILD_SPEC §1 / §2:
* `trace_id` and `span_id` are generated by the OTel SDK (spec-compliant hex).
  Never hand-rolled UUIDs.
* The per-trace monotonic `seq` is a SEPARATE integer field, assigned at the
  proxy (Phase 1). This module only deals with the OTel ID generation; the
  seq counter lives in `whence.forensics` from Phase 1 onward.

This module is idempotent: calling :func:`init_tracing` multiple times is safe.
"""
from __future__ import annotations

import threading
from typing import Final

from opentelemetry import trace as _otel_trace
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.id_generator import RandomIdGenerator
from opentelemetry.trace import Tracer

from whence.config import get_settings

_INIT_LOCK: Final[threading.Lock] = threading.Lock()
_INITIALIZED: bool = False
_ID_GENERATOR: Final[RandomIdGenerator] = RandomIdGenerator()


def init_tracing(*, service_name: str = "whence") -> None:
    """Install a TracerProvider once per process.

    * In DEMO MODE (and when no Application Insights connection string is set)
      we register a bare :class:`TracerProvider` with no exporter. Spans are
      still produced; they just do not leave the process. This keeps unit
      tests fast and offline.
    * In AZURE MODE with a connection string present, `configure_azure_monitor`
      is used (it wires its own provider + exporter). We detect the
      already-installed provider and skip the bare init.

    Either way, subsequent code calls :func:`get_tracer` and gets a working
    tracer that produces spec-compliant 128-bit hex `trace_id` / 64-bit hex
    `span_id`.
    """
    global _INITIALIZED
    if _INITIALIZED:
        return

    with _INIT_LOCK:
        if _INITIALIZED:
            return

        settings = get_settings()
        existing = _otel_trace.get_tracer_provider()
        already_has_real_provider = isinstance(existing, TracerProvider)

        if (
            not settings.demo_mode
            and settings.applicationinsights_connection_string
            and not already_has_real_provider
        ):
            # Lazy import: keeps demo-mode startup fast and lets the package
            # build green on machines that never plan to use Azure Monitor.
            from azure.monitor.opentelemetry import configure_azure_monitor

            configure_azure_monitor(
                connection_string=settings.applicationinsights_connection_string,
                logger_name=service_name,
            )
        elif not already_has_real_provider:
            _otel_trace.set_tracer_provider(TracerProvider())

        _INITIALIZED = True


def get_tracer(instrumentation_name: str = "whence") -> Tracer:
    """Return a Tracer, installing a provider if needed."""
    if not _INITIALIZED:
        init_tracing()
    return _otel_trace.get_tracer(instrumentation_name)


def new_trace_id_hex() -> str:
    """Return a fresh 128-bit hex trace ID from the OTel SDK ID generator.

    Spec §2 / §1.4: "IDs: `trace_id`/`span_id` are generated by the OTel SDK
    (spec-compliant hex), never hand-rolled UUIDs." This function is the ONE
    place Whence mints trace IDs outside an active span. Phase 1 uses it
    when seeding a synthetic trace for replay tests; production traces are
    minted by the live OTel span context.
    """
    return _format_trace_id(_ID_GENERATOR.generate_trace_id())


def new_span_id_hex() -> str:
    """Return a fresh 64-bit hex span ID from the OTel SDK ID generator."""
    return _format_span_id(_ID_GENERATOR.generate_span_id())


def _format_trace_id(value: int) -> str:
    """Zero-padded 32-char (128-bit) lowercase hex, matching W3C Trace Context."""
    return f"{value:032x}"


def _format_span_id(value: int) -> str:
    """Zero-padded 16-char (64-bit) lowercase hex, matching W3C Trace Context."""
    return f"{value:016x}"


def reset_tracing_for_tests() -> None:
    """Tests that need to reinit tracing call this.

    Production code MUST NOT call this — re-installing a TracerProvider on a
    running app loses spans.
    """
    global _INITIALIZED
    with _INIT_LOCK:
        _INITIALIZED = False
